### ISSUE TITLE
Jak 3 Decomp Checklist

### ISSUE THREAD

**Issue by water111** [open-goal/jak-project#3309]
Before we "officially" start Jak 3

- [x] Generate `all-types.gc` file
  - [x] Make sure we don't have an off-by-4-bytes issue like we did in jak 2 for children of process
- [x] Decompile everything in `KERNEL.CGO`
  - [x] Port kernel context switch stuff
  - [x] Get the "kernel test" to pass, which verifies spawning process/switching threads in GOAL.
- [x] Get offline tests running
- [x] Get type consistency test running
- [x] Update documentation/ping people who were interested

Also a list of stuff that's separate from decompilation, but we need to do eventually:

- [ ] Jak 3 Overlord (this is a big one, it got totally rewritten!)
- [ ] v5 linker to load v5 object files from the original game (we don't need to support all cases from the original game, only ones needed for level files)
- [ ] Setting up the build system fully
- [ ] merc/tie/tfrag/shrub/texture extraction
- [ ] Setting up graphics stuff
